Flag_Set(FLAG_TYPE.INFO,FLAG_INFO.LV,Flag_Get(FLAG_TYPE.STATIC,FLAG_STATIC.LV));
Flag_Set(FLAG_TYPE.INFO,FLAG_INFO.TIME,Flag_Get(FLAG_TYPE.STATIC,FLAG_STATIC.TIME));
Flag_Set(FLAG_TYPE.INFO,FLAG_INFO.ROOM,Flag_Get(FLAG_TYPE.STATIC,FLAG_STATIC.ROOM));
Flag_Set(FLAG_TYPE.INFO,FLAG_INFO.NAME,Flag_Get(FLAG_TYPE.STATIC,FLAG_STATIC.NAME));
return true;