///@arg slot
function Player_Save() {
	var SLOT=argument[0];

	Flag_SetSaveSlot(SLOT);

	Flag_Save(FLAG_TYPE.STATIC);
	Flag_Set(FLAG_TYPE.INFO,FLAG_INFO.LV,Flag_Get(FLAG_TYPE.STATIC,FLAG_STATIC.LV));
	Flag_Set(FLAG_TYPE.INFO,FLAG_INFO.TIME,Flag_Get(FLAG_TYPE.STATIC,FLAG_STATIC.TIME));
	Flag_Set(FLAG_TYPE.INFO,FLAG_INFO.ROOM,Flag_Get(FLAG_TYPE.STATIC,FLAG_STATIC.ROOM));
	Flag_Set(FLAG_TYPE.INFO,FLAG_INFO.NAME,Flag_Get(FLAG_TYPE.STATIC,FLAG_STATIC.NAME));
	Flag_Save(FLAG_TYPE.INFO);

	return true;


}
